site_name: BRISA Helpdesk

theme:
  name: material
  logo: images/logo-2.png
  favicon: images/logo-2.png

nav: 
  - Início: index.md
  - Iniciação:
    - Documento de abetura: initiation/project-charter.md
  - Planejamento:
    - Documento de ferramentas: planning/tech-stack.md
    - Documento de requisitos: planning/requirements-agile-catalog.md
    - Documento de arquitetura: planning/system-architecture/system-architecture.md
  - Testing: planning/database/tables.md