site_name: BRISA Helpdesk

theme:
  name: material
  logo: images/logo-2.png
  favicon: images/logo-2.png

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav: 
  - Início: index.md
  - Iniciação:
    - Documento de abetura: initiation/project-charter.md
  - Planejamento:
    - Documento de ferramentas: planning/tech-stack.md
    - Documento de requisitos: planning/requirements-agile-catalog.md
    - Documento de arquitetura: planning/system-architecture/system-architecture.md
    - Documentos de processos:
      - Processo de criação de cliente: planning/system-processes/create-new-client.md
    - Documentos de banco de dados:
      - Padrão de nomenclatura: planning/database/naming-convetions.md
      - Documento de modelo relacional: planning/database/relational-model.md
